CREATE DATABASE zoo;

USE zoo;

DROP TABLE IF EXISTS tier;
DROP TABLE IF EXISTS gehege_pfleger;
DROP TABLE IF EXISTS pfleger;
DROP TABLE IF EXISTS tierart;
DROP TABLE IF EXISTS kontinent;


CREATE TABLE kontinent(
	KontinentID INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(100) NOT NULL);


CREATE TABLE tierart(
	TierartID INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(100) NOT NULL);


CREATE TABLE gehege(
	GehegeID INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(100) NOT NULL,
	KontinentID INT,
	FOREIGN KEY (KontinentID) REFERENCES kontinent(KontinentID) );


CREATE TABLE tier(
	TierID INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(100) NOT NULL,
	Geburtsjahr VARCHAR(5) NOT NULL,
	GehegeID INT,
	TierartID INT,
	FOREIGN KEY (GehegeID) REFERENCES gehege(GehegeID),
	FOREIGN KEY (TierartID) REFERENCES tierart(TierartID) );


CREATE TABLE pfleger(
	PflegerID INT PRIMARY KEY AUTO_INCREMENT,
	Vorname VARCHAR(100) NOT NULL,
	Nachname VARCHAR(100) NOT NULL);



CREATE TABLE gehege_pfleger(
	GPID INT PRIMARY KEY AUTO_INCREMENT,
	GehegeID INT,
	PflegerID INT,
	Hauptpfleger INT(1) NOT NULL,
	FOREIGN KEY (GehegeID) REFERENCES gehege(GehegeID),
	FOREIGN KEY (PflegerID) REFERENCES pfleger(PflegerID) );
